#!/bin/bash
sudo apt install -y curl
mkdir -p ~/.config/nvim
ln -s "${PWD}/../dotfiles/.config/nvim/init.vim" "${HOME}/.config/nvim/"

rm ~/.bashrc
ln -s "${PWD}/../dotfiles/.bashrc" "${HOME}/.bashrc"
ln -s "${PWD}/../dotfiles/.zshrc" "${HOME}/.zshrc"

mkdir -p ~/.vim/colors
cd ~/.vim/colors
curl -O https://raw.githubusercontent.com/nanotech/jellybeans.vim/master/colors/jellybeans.vim
curl -O https://raw.githubusercontent.com/NLKNguyen/papercolor-theme/master/colors/PaperColor.vim

sudo apt update
sudo apt install -y gnome-tweaks
sudo apt install -y gnome-shell-extensions
sudo apt install -y gnome-shell-extension-manager

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# hydroxide, requires for this to live in ~/git/repo
sudo apt install golang
cd ~/git
git clone https://github.com/emersion/hydroxide.git
cd hydroxide
go build ./cmd/hydroxide
sudo cp ./hydroxide /usr/local/bin
sudo cp ~/git/config_files/daemon/hydroxide.service /etc/systemd/system
sudo systemctl daemon-reexec
sudo systemctl enable --now hydroxide
echo "Now do $ hydroxide auth <username>"
echo "Remember all plain. IMAP 1143 SMTP 1025"
